apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-resources-hyper-deployment
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}-resources-hyper
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-resources-hyper
    spec:
      containers:
        - name: resources-hyper-container
          image: registry.hyper.mathematikoi.co/resources.service.hyper
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-resources-configmap
          ports:
            - containerPort: {{ .Values.configuration.port }}
              name: {{ .Release.Name }}-r-h-c-p
          imagePullPolicy: Always