apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-template-service-hyper-deployment
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}-template-service-hyper
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-template-service-hyper
    spec:
      containers:
        - name: template-service-hyper-container
          image: registry.hyper.mathematikoi.agency/template.service.hyper::{{ .Chart.Version }}
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-template-service-hyper-configmap
            - secretRef:
                name: discovery-hyper-password
                key: DISCOVERY_HYPER_PASSWORD
          ports:
            - containerPort: {{ .Values.configuration.port }}
              name: http
          imagePullPolicy: Always
      imagePullSecrets:
        - name: docker-registry-credentials
      