apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-template-service-hyper-service
spec:
  selector:
    app: {{ .Release.Name }}-template-service-hyper
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP