apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-resources-hyper-service
spec:
  selector:
    app: {{ .Release.Name }}-resources-hyper
  ports:
    - name: {{ .Release.Name }}-r-h-s-p
      port: 80
      targetPort: {{ .Release.Name }}-r-h-c-p
      protocol: TCP