name: build

on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: build and publish
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: build image
        run: "docker build -t registry.hyper.mathematikoi.co/{{service.name}}.service.hyper:$\{{  github.ref_name }} ."
      - name: push image
        run: "docker push registry.hyper.mathematikoi.co/{{service.name}}.service.hyper:$\{{  github.ref_name }}"